modLoader = "lowcodefml"
loaderVersion = "[38,)"
license = "All-Rights-Reserved"
[[mods]]
modId = "chosen_origins_greek"
version = "1.0.0"
displayName = "Chosen Origins: Greek"
description = "Chosen Origins: Greek adds new thematic origins inspired by Greek mythology and history to the Origins mod, providing players with unique starting bonuses and gameplay changes."
authors="Kerberus, jetuit"
